# description
name: "hues"
description: "A nonexistent tool for working with colors."
keywords: "color, design, webdesign, css"
author: "Leszek Pietrzak"

# address settings
baseurl: "http://hues.smutnyleszek.com"
rootSiteUrl: "http://smutnyleszek.com"

# site configuration
safe: true
quiet: false
future: true
encoding: utf-8
markdown: kramdown
kramdown:
    auto_ids: false
timezone: Europe/Warsaw

# excludes
exclude:
    - src
    - test
    - node_modules
    - LICENSE
    - README.md
    - TODO.md
    - jasmine.json
    - package.json
